### ISSUE TITLE
Uncaught TypeError: Cannot read property 'pick' of undefined

### ISSUE THREAD

**Issue by anilmaurya** [DudaDev/ember-cli-filepicker#1]
I am getting error 'Uncaught TypeError: Cannot read property 'pick' of undefined' after following mentioned steps in Readme.

I checked on console, filepicker is defined.

Am I missing anything ?

**Comment by yonida** [comment]
did you take a look at the dummy example? it's working there without errors.

**Comment by yonida** [comment]
I pushed a fix, it should be ok now.
