### ISSUE TITLE
A helper named 'ember-filepicker' could not be found

### ISSUE THREAD

**Issue by RBdevelop** [DudaDev/ember-cli-filepicker#13]
I keep getting this error `A helper named ember-filepicker' could not be found` 

```
<div class="hide-upload-button" {{action 'openPicker'}}>
          <div class="preview-button">Edit</div>
          {{#if isPickerOpen}}
            {{ember-filepicker  pickerOptions=pickerOptions storeOptions=storeOptions 
             onSelection='pickerSelected' onClose='pickerClose' onError='pickerError'}}
          {{/if}}
        </div>
</div> 
```

My product controller 

```
  openPicker : function() {
      this.set('isPickerOpen', true);
    },

    pickerClose : function(  ){
      this.set('isPickerOpen', false);
    },

    pickerError : function(){
      this.send('pickerClose');
    },

    pickerSelected : function(selection){
      if(selection[0]) {
        let model = get(this, 'model');
        let imageUrl = '';

        if(selection[0].key) {
          imageUrl = [get(this, 's3Url'), selection[0].container, selection[0].key].join('/');
        } else {
          imageUrl = selection[0].url;
        }

        model.set('imageUrl', imageUrl);
      }

      this.send('pickerClose');
    }
```

**Comment by RBdevelop** [comment]
Any ideas @yonida  @geymed  @ramybenaroya @justtal  @mminkoff

**Comment by mminkoff** [comment]
That should certainly work.  You're sure the add-on is installed correctly?

**Comment by RBdevelop** [comment]
@mminkoff  I believe so . Do you see anything that would interfere? 
"devDependencies": {
    "broccoli-asset-rev": "^2.0.2",
    "ds-ember-data": "^1.0.8",
    "ember-cli": "0.2.2",
    "ember-cli-app-version": "0.3.3",
    "ember-cli-dependency-checker": "0.0.8",
    "ember-cli-es5-shim": "^0.1.1",
    "ember-cli-filepicker": "0.1.95",
    "ember-cli-ic-ajax": "0.1.1",
    "ember-cli-inject-live-reload": "^1.3.0",
    "ember-cli-mirage": "0.1.5",
    "ember-cli-mocha": "^0.6.0",
    "ember-cli-notifications": "2.1.0",
    "ember-cli-uglify": "1.0.1",
    "ember-data": "1.0.0-beta.16.1",
    "ember-export-application-global": "^1.0.2",
    "ember-select-2": "^1.2.0",
    "ember-validations": "git+https://github.com/dockyard/ember-validations.git#aa5df24bc96299daadddec8164853545356465f2",
    "underscore": "^1.8.3"
  },
  "keywords": [
    "ember-addon"
  ],
  "dependencies": {
    "ember-cli-htmlbars": "0.7.4",
    "ember-cli-babel": "^4.0.0"
  },
  "ember-addon": {
    "configPath": "tests/dummy/config"

**Comment by mminkoff** [comment]
You're using a very old version of ember-cli.  I bet that's the problem.  There were breaking changes leading up to 1.0 that are probably affecting you.

**Comment by RBdevelop** [comment]
that was the source of this issue. Thanks!
