### ISSUE TITLE
Reference my demo if you'd like

### ISSUE THREAD

**Issue by mminkoff** [DudaDev/ember-cli-filepicker#2]
Hi folks - good job on creating this add-on!  I've used it for a demo I'm going to do for the Ember NYC meetup tonight.  Here's the demo: https://github.com/mminkoff/ember-cli-filepicker-demo

Two bits of feedback:
- It'd be great to be able to add a button to open and close the picker rather than having to manage that outside of the add-on.  I imagine you have that in mind.  That is how I expected it to work.
- It would also be great to have an easier way to run filepicker.stat.  Or perhaps there's a better way than I used to access the filepicker object?  

I'm not sure this is the correct place to put this, so my apologies if not.

Thanks!

**Comment by yonida** [comment]
Hi there, nice to hear that you like our add-on, and a very nice demo!
- We strongly believe that the component should be displayed once it is mounted in the view, so managing the show/hide should be handled outside the component.
  This way we can support different use cases such as showing the component without pressing a button.
- We pushed an update which now enables you to use the filepicker object as an injected service.
  You can check the Notes section in our readme for an example.
  Please note that we also changed the location of the filepickerKey (directly under ENV)

P.S. how was the Ember NYC meetup? do you guys video these meetups?

**Comment by mminkoff** [comment]
Here's video of my lightning talk: https://www.youtube.com/watch?v=dpaw4oIAEA0&t=629

Glad to hear you've exposed the filepicker object - I was thinking injected service too.  I'll try to get that updated shortly.  (this is the clunkiness I referred to in my talk by the way - great that you got it updated!)

I hear you on showing the modal that way.  I think at least being clearer about that in the README would help tremendously, as I thought something was broken when I first tried to use it.  

I guess my strongest argument for doing it with a button is that it would be more in line with the way filepicker itself works.  With filepicker itself, you don't add the modal - you add the ability to open the modal.  Plus, while you're solving for a specific use case, almost everyone will have this behind a button and so they'll need to solve that problem each time.  

Do you plan to expand the capabilities?  How about drag and drop widgets or other widgets?  Perhaps you could provide multiple components - ember-filepicker-modal (like you have but renamed), ember-filepicker-button, ember-filepicker-droppane, etc.

**Comment by mminkoff** [comment]
I updated my demo to use your latest version - much cleaner!

**Comment by yonida** [comment]
Hey Max, I'm glad you like our updated version.
I watched your talk and it was very cool !

Here at duda we need the filepicker to behave as I mentioned above, so that's how we implemented it.
I guess we won't expand the add-on capabilities since we don't really need other capabilities from it.
On the other hand, anyone is welcome to fork and create PR's, and we will merge them to this branch.

**Comment by mminkoff** [comment]
Totally fair.  I'd be happy to fork and create PRs.  I'd just want to know that I'd be headed in a direction that you'd support, so perhaps you could provide a little feedback on my suggestions?
